# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointByLocalCartesian
                                 A QGIS plugin
 Calculate latitude and longitude of point given in Cartesian coordinate system
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-17
        copyright            : (C) 2019 by Paweł Strzelewicz
        email                : aviationgisapp@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointByLocalCartesian class from file PointByLocalCartesian.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .point_locac_cartesian import PointByLocalCartesian
    return PointByLocalCartesian(iface)
